default_size: square:12x12x6
brands:
  - name: Bar-B-Chef Offset
    stub: bar-b-chef-offset
  - name: Brinkmann Cimarron Deluxe
    stub: brinkmann-cimarron-deluxe
  - name: Brinkmann Smoke King Deluxe
    stub: brinkmann-smoke-king-deluxe
  - name: Brinkmann Smoke N' Pit
    stub: brinkmann-smoke-n-pit
    size: square:9x12x8
  - name: Brinkmann Trailmaster Limited
    stub: brinkmann-trailmaster-limited
  - name: Browning Offset
    stub: browning-offset
    size: square:11x17x8
  - name: Char-Broil American Gourmet 700 Series
    stub: charbroil-american-gourmet-700
    size: square:10x12x6
  - name: Char-Broil Silver
    stub: charbroil-silver
    size: square:9x14x5
  - name: Char-Broil Oklahoma Joe
    stub: charbroil-oklahoma-joe
  - name: Chargriller Duo
    stub: chargriller-duo
  - name: Chargriller Side Fire Box
    stub: chargriller-side-fire-box
  - name: Chargriller Smokin' Pro
    stub: chargriller-smokin-pro
  - name: Kingsford Wagon Boss
    stub: kingsford-wagon-boss
    size: square:10x14x6
  - name: Landmann Black Dog 42XT
    stub: landmann-black-dog-42xt
    size: square:14x15x7
  - name: New Braunsfel Bandera
    stub: new-braunsfel-bandera
  - name: New Braunsfel Longhorn Deluxe
    stub: new-braunsfel-longhorn-deluxe
    size: square:15x15x8
  - name: Old Country 20&quot;
    stub: old-country-20
  - name: Old Country BBQ Pits Pecos
    stub: old-county-bbq-pits-pecos
    size: square:15x15x8
  - name: Outdoor Gourmet Triton
    stub: outdoor-gourmet-triton
    size: square:10x14x6
  - name: RD Horizon Offset 20&quot;
    stub: rd-horizon-offset-20
    size: square:15x15x8
  - name: RD Horizon Offset 24&quot;
    stub: rd-horizon-offset-24
    size: square:15x15x8
  - name: Weber Smokey Mountain Cooker 18.5"
    stub: weber-smokey-mountain-cooker-18-5
    size: round:12x6
pricing:
  material:
    carbon: 60
    stainless: 525
  labor:
    carbon: 30
    stainless: 30
  custom: 15
  markup: 2.1
weight:
    carbon: 57.6
    stainless: 65.6
feedback:
  to: kwilson@charcoalbasket.com
  subject: charcoalbasket.com Form Submission
analytics:
  code: UA-27811127-1
checkout:
  tax:
    state: TN
    rate: 0.0925
  shipping:
    from:
      city: Franklin
      state: TN
      country: US
      postal-code: 37067
environment:
  dev:
    checkout:
      url: https://www.sandbox.paypal.com/cgi-bin/webscr
      account: kerry-facilitator@allthingswilson.com
    analytics:
      code: UA-XXXXXXXX-1
  prod:    
    checkout:
      url: https://www.paypal.com/cgi-bin/webscr
      account: kerry@allthingswilson.com